// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeWebApp.Data;

#nullable disable

namespace RecipeWebApp.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    partial class RecipeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeRecipeCategory", b =>
                {
                    b.Property<int>("RecipeCategoriesCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipesRecipeId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeCategoriesCategoryId", "RecipesRecipeId");

                    b.HasIndex("RecipesRecipeId");

                    b.ToTable("RecipeRecipeCategory");
                });

            modelBuilder.Entity("RecipeRecipeTag", b =>
                {
                    b.Property<int>("RecipeTagsTagId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipesRecipeId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeTagsTagId", "RecipesRecipeId");

                    b.HasIndex("RecipesRecipeId");

                    b.ToTable("RecipeRecipeTag");
                });

            modelBuilder.Entity("RecipeWebApp.Models.Abstracts.BaseImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageType")
                        .HasColumnType("integer");

                    b.Property<string>("MidiumImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmallImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Images", (string)null);

                    b.HasDiscriminator<int>("ImageType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RecipeWebApp.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<int?>("IngredientMeasurementUnitMeasurementUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Quantity")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("IngredientId");

                    b.HasIndex("IngredientMeasurementUnitMeasurementUnitId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RecipeWebApp.Models.IngredientMeasurementUnit", b =>
                {
                    b.Property<int>("MeasurementUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeasurementUnitId"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("MeasurementUnitId");

                    b.ToTable("IngredientMeasurementUnits");
                });

            modelBuilder.Entity("RecipeWebApp.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSubRecipe")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastUpdated")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.HasKey("RecipeId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeWebApp.Models.RecipeCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("RecipeCategories");
                });

            modelBuilder.Entity("RecipeWebApp.Models.RecipeStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StepId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<short>("StepOrder")
                        .HasColumnType("smallint");

                    b.HasKey("StepId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("RecipeWebApp.Models.RecipeSubrecipe", b =>
                {
                    b.Property<int>("ParentRecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("SubrecipeId")
                        .HasColumnType("integer");

                    b.HasKey("ParentRecipeId", "SubrecipeId");

                    b.HasIndex("SubrecipeId");

                    b.ToTable("RecipeSubrecipe", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeSubrecipes_NoSelfReference", "\"ParentRecipeId\" <> \"SubrecipeId\"");
                        });
                });

            modelBuilder.Entity("RecipeWebApp.Models.RecipeTag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId");

                    b.ToTable("RecipeTags");
                });

            modelBuilder.Entity("RecipeWebApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateOnly>("DayRegistered")
                        .HasColumnType("date");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecipeWebApp.Models.RecipeImage", b =>
                {
                    b.HasBaseType("RecipeWebApp.Models.Abstracts.BaseImage");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.HasIndex("RecipeId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("RecipeWebApp.Models.UserImage", b =>
                {
                    b.HasBaseType("RecipeWebApp.Models.Abstracts.BaseImage");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("RecipeRecipeCategory", b =>
                {
                    b.HasOne("RecipeWebApp.Models.RecipeCategory", null)
                        .WithMany()
                        .HasForeignKey("RecipeCategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeWebApp.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeRecipeTag", b =>
                {
                    b.HasOne("RecipeWebApp.Models.RecipeTag", null)
                        .WithMany()
                        .HasForeignKey("RecipeTagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeWebApp.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeWebApp.Models.Ingredient", b =>
                {
                    b.HasOne("RecipeWebApp.Models.IngredientMeasurementUnit", "IngredientMeasurementUnit")
                        .WithMany()
                        .HasForeignKey("IngredientMeasurementUnitMeasurementUnitId");

                    b.HasOne("RecipeWebApp.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientMeasurementUnit");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeWebApp.Models.Recipe", b =>
                {
                    b.HasOne("RecipeWebApp.Models.User", "Author")
                        .WithMany("Recipes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("RecipeWebApp.Models.RecipeStep", b =>
                {
                    b.HasOne("RecipeWebApp.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeWebApp.Models.RecipeSubrecipe", b =>
                {
                    b.HasOne("RecipeWebApp.Models.Recipe", "ParentRecipe")
                        .WithMany("Subrecipes")
                        .HasForeignKey("ParentRecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeWebApp.Models.Recipe", "Subrecipe")
                        .WithMany("ParentRecipes")
                        .HasForeignKey("SubrecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentRecipe");

                    b.Navigation("Subrecipe");
                });

            modelBuilder.Entity("RecipeWebApp.Models.RecipeImage", b =>
                {
                    b.HasOne("RecipeWebApp.Models.Recipe", "Recipe")
                        .WithOne("RecipeImage")
                        .HasForeignKey("RecipeWebApp.Models.RecipeImage", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeWebApp.Models.UserImage", b =>
                {
                    b.HasOne("RecipeWebApp.Models.User", "User")
                        .WithOne("UserImage")
                        .HasForeignKey("RecipeWebApp.Models.UserImage", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeWebApp.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("ParentRecipes");

                    b.Navigation("RecipeImage");

                    b.Navigation("Steps");

                    b.Navigation("Subrecipes");
                });

            modelBuilder.Entity("RecipeWebApp.Models.User", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("UserImage");
                });
#pragma warning restore 612, 618
        }
    }
}
